### ISSUE TITLE
feature: triggers

### ISSUE THREAD

**Issue by majidaldo** [ESSS/conda-devenv#108]
Add triggers section to execute arbitrary code.
Use case: To trigger setup codes.

I saw some of the issues in #84 . I really like the limited scope of conda-devenv. At the same time, I want to be able to 'build'/setup a project made of many devenvs with dependencies between them without having to go full on conda build.

The includes already track dependencies, so it would be nice to make use of them to automate setups.

**Comment by prusse-martin** [comment]
We have written tool called [`deps`](https://github.com/ESSS/deps).
I know the documentation is a bit lacking sorry.
It is available in conda forge: `conda install -c conda-forge deps`
Check `deps --help` maybe it can help you.
We use it along side [invoke](https://github.com/pyinvoke/invoke) to implement the code to be executed.

**Comment by majidaldo** [comment]
> We have written tool called [`deps`](https://github.com/ESSS/deps).
> I know the documentation is a bit lacking sorry.
> It is available in conda forge: `conda install -c conda-forge deps`
> Check `deps --help` maybe it can help you.
> We use it along side [invoke](https://github.com/pyinvoke/invoke) to implement the code to be executed.
> Let us know if that helps or you really need this built in conda-devenv.

*exactly* what i did!!

**Comment by majidaldo** [comment]
on that note, sometimes i wonder if this a job for `make`.

**Comment by nicoddemus** [comment]
Thanks @majidaldo for the suggestion.

But we really do believe the best approach is to document `deps` for now, because it is a more focused tool and it is simple anyway for the user to use, just:

```
conda install deps conda-devenv
```

I've created https://github.com/ESSS/deps/issues/12 for us to improve the documentation at some point.

Thanks again!

**Comment by prusse-martin** [comment]
@majidaldo

I know this is not a full fledged documentation but I add the contents of `deps --help` to the deps readme.
https://github.com/ESSS/deps/blob/master/README.md
