### ISSUE TITLE
Incorrect rendering of pip dependencies with flags

### ISSUE THREAD

**Issue by phausamann** [ESSS/conda-devenv#113]
Defining multiple dependencies in the `pip` section with flags such as  `--editable/-e`:

```
dependencies:
- pip:
  - --editable path/to/first/package
  - --editable path/to/second/package
name: pip_editable_test
```

generates this:

```
dependencies:
- pip:
  - --editable path/to/first/package,path/to/second/package
name: pip_editable_test
```

which causes `pip` to fail because of the comma. And even replacing the comma with a space produces an incorrect result because only the first dependency is installed as editable.

**Comment by phausamann** [comment]
Seems to be pretty much the same issue as #91 - easy fix would be to add  `or dep.startswith("-")` [here](https://github.com/ESSS/conda-devenv/blob/1d57f4922384c7c3f3938ba140d9d2bd775e045f/conda_devenv/devenv.py#L255).

**Comment by nicoddemus** [comment]
Indeed, thanks!

A PR would be appreciated if you want to give it a try. 👍
