### ISSUE TITLE
How to update the environment variables only? 

### ISSUE THREAD

**Issue by EricAtORS** [ESSS/conda-devenv#123]
Hi,

How can I update just the environment variables contained in my devenv.yml file?
Manual or automatic are suitable for me.
I'm mostly editing the environment section and not the packages themselves and would rather just edit a file manually if needed instead of waiting for the process to finish,

**Comment by prusse-martin** [comment]
There is not automated way to update only the environment variables.
Manually it is possible to edit the files:

- <conda-envirroment-path>\etc\conda\activate.d\devenv-vars.bat
- <conda-envirroment-path>\etc\conda\deactivate.d\devenv-vars.bat

**Comment by EricAtORS** [comment]
Perfect. Thank you!
