### ISSUE TITLE
see pixi

### ISSUE THREAD

**Issue by majidaldo** [ESSS/conda-devenv#217]
Hey guys.

I've been a fan of this project but it looks like pixi will just subsume the functionality I'm seeing here.

Personally, I'm really liking [muli env](https://pixi.sh/latest/features/multi_environment/) .

I hope you can provide guidance to this project from your experience. Thank you for this great tool!

**Comment by nicoddemus** [comment]
@majidaldo we are indeed following pixi development closely... hopefully we can eventually migrate to `pixi` and drop conda and conda-devenv altogether. 👍
