### ISSUE TITLE
Add it to Conda Community wiki

### ISSUE THREAD

**Issue by fogo** [ESSS/conda-devenv#27]
Guys, once this tool is mature I suggest adding to [Conda wiki](https://github.com/conda/conda/wiki/Conda-Community). It may help getting noticed and helping others ;)

**Comment by nicoddemus** [comment]
Sure thing! We plan to also send an email to their mailing list (if they are OK with announcements that is).

**Comment by nicoddemus** [comment]
@gqmelo just realized [exec-wrappers](https://github.com/gqmelo/exec-wrappers) is not mentioned there, perhaps it should be?

**Comment by nicoddemus** [comment]
Following up: conda-forge/staged-recipes#2657

**Comment by nicoddemus** [comment]
Just added it to the wiki. 😁
