### ISSUE TITLE
Add a way to identify if the current file is the "main" devenv file

### ISSUE THREAD

**Issue by lvoliveira** [ESSS/conda-devenv#71]

**Comment by prusse-martin** [comment]
2 devenv files with conflicting configurations and a dependency relationship. This will allow the author the use jinja rendering to ommit the offending configuration when the file is included from other env definition file.

**Comment by prusse-martin** [comment]
`is_included` is my suggestion.

`is_root` is not my first choice since we define `root` as the containing directory for the file being parsed.
and `is_main` sounds to vague.

**Comment by nicoddemus** [comment]
👍 for `is_included`
