### ISSUE TITLE
linux, macOS, and win variables instead of sys.platform.startswith(...)

### ISSUE THREAD

**Issue by allanleal** [ESSS/conda-devenv#74]
This is just a suggestion to define (boolean) python variables `linux`, `macOS` (or `osx`), and `win32` such that the following:

```
{% if sys.platform.startswith('linux') or sys.platform.startswith('osx') %}
```
could be replaced with:

```
{% if linux or osx %}
```

Are there any limitations in the tools used by `conda-devenv` that prevent this simpler usage?

**Comment by prusse-martin** [comment]
AFAIK it is just a question of adding those booleans to [`jinja_dict` in the function `render_jinja`](https://github.com/ESSS/conda-devenv/blob/master/conda_devenv/devenv.py#L15) so they are avalable durring jinja rendering.

**Comment by allanleal** [comment]
In addition, a string variable `arch` or `architecture` that gets set to `64bit` or `32bit`, by a call to `platform.architecture()[0]`, would be useful.

**Comment by nicoddemus** [comment]
Agreed to all those. Should be a nice first contribution if you are inclined @allanleal. 😉

**Comment by marcelotrevisani** [comment]
I think would be useful to have an ``unix`` variable instead of doing ``linux or osx``

**Comment by allanleal** [comment]
@nicoddemus Sure! :) I'll see what I can do.
@marcelotrevisani Sure, `unix === linux or osx`, right.

**Comment by tadeu** [comment]
Awesome idea!

`conda build` has these selectors: https://conda.io/projects/conda-build/en/latest/source/define-metadata.html#preprocessing-selectors, we can try to keep `conda-devenv` compatible as more variables are added.

**Comment by allanleal** [comment]
@tadeu Nice list as a reference for what should be supported.

**Comment by prusse-martin** [comment]
I will sugest to left out  py27, py34, py35, and py36. 

> py27 | True if the Python version is 2.7. Use of this selector is discouraged in favor of comparison operators (e.g. py==27).

**Comment by nicoddemus** [comment]
> I will suggest to left out py27, py34, py35, and py36.

Definitely. When we are parsing the `devenv` file, we don't actually know which is the Python version which will be used to create the environment, because the target environmnt's Python is defined in the `devenv` file itself.

**Comment by prusse-martin** [comment]
Yes you are right. I say we drop all python related vars. Since to the environment being created the info from the root (base) environment is not really useful and can became confusing.

**Comment by allanleal** [comment]
Below is how `jinja_dict` could be modified to include the [preprocessing selectors](https://conda.io/projects/conda-build/en/latest/source/define-metadata.html#preprocessing-selectors) used by conda-build:

~~~python

pyversion = platform.python_version().split('.')

iswin = sys.platform.startswith('win')
islinux = sys.platform.startswith('linux')
isosx = sys.platform.startswith('darwin')

is32bit = '32bit' == platform.architecture()[0]
is64bit = not is32bit

jinja_dict = {
    "root": os.path.dirname(os.path.abspath(filename)),
    "os": os,
    "sys": sys,
    "platform": platform,
    "x86": 'x86' == platform.machine(),
    "x86_64": 'x86_64' == platform.machine(),
    "linux": islinux,
    "linux32": islinux and is32bit,
    "linux64": islinux and is64bit,
    "armv6l": None,
    "armv7l": None,
    "ppc64le": None,
    "osx": isosx,
    "unix": islinux or isosx,
    "win": iswin,
    "win32": iswin and is32bit,
    "win64": iswin and is64bit,
    "py": int(pyversion[0] + pyversion[1]),
    "py2k": pyversion[0] == 2,
    "py3k": pyversion[0] == 3,
    "py27": pyversion[0] == 2 and pyversion[1] == 7,
    "py34": pyversion[0] == 3 and pyversion[1] == 4,
    "py35": pyversion[0] == 3 and pyversion[1] == 5,
    "py36": pyversion[0] == 3 and pyversion[1] == 6
}
~~~

Missing selectors are `armv6l`, `armv7l`, and `ppc64le` (I'lll have to research more :)). We can remove the `pyXY` variables as requested by @prusse-martin .

Comments welcome.

**Comment by nicoddemus** [comment]
Looks good! The `py*` variables should not go in as mentioned. 👍

**Comment by edisongustavo** [comment]
I know the discussion is over already, but I'd just like to add that add anything that is "package related" should **NOT** be added in these selectors.

The main reason is that these kind of selectors (package related) might not make sense in some environments, leading to confusion.

For example:

```yaml
packages:
  - cmake  # [py3]
```
(`environment.devenv.yml`)

What would happen if I call `conda devenv` ? Remember that there is no python being installed in this environment. Will the environment be empty?

It would just lead to confusion. So good call there @prusse-martin .
