### ISSUE TITLE
Empty includes causes error: NoneType object is not iterable

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/conda-devenv#85]
`environment.devenv.yml`:

```
includes:
```

Results in:

```
  File "W:\Miniconda\lib\site-packages\conda_devenv\devenv.py", line 41, in handle_includes
    for included_filename in yaml_dict.get("includes", []):
TypeError: 'NoneType' object is not iterable
```

That line in `handle_includes` should be changed to:

```python
for included_filename in yaml_dict.get("includes") or []:
```

**Comment by tadeu** [comment]
I wish other tools had this kind of care when dealing with pre-processed YAML, i.e., allowing empty "sections" :D

**Comment by gcardozo123** [comment]
Should we print some kind of warning when that happens?

**Comment by nicoddemus** [comment]
No, just ignoring it is fine. 👍
