### ISSUE TITLE
Package patter matching should be case insensitive

### ISSUE THREAD

**Issue by xiamubobby** [ESSS/conda-devenv#95]
https://github.com/ESSS/conda-devenv/blob/4db6cc7e4214f8b417cd6b784fa03a4652d66739/conda_devenv/devenv.py#L193-L198

Though elegantly, but suppose some reasonably good library are not following the convention. It leave us no work around for now except for replacing the entire function as a hack.

Say httpspypi.org/project/ConfigArgParse

```
File"C:\Users\dummy\anaconda\Anaconda_py3.6.4.4.0.\\ py36\lib\site
 packages conda deveny devenv py". line 221, in merge_dependencies_version_specifications
 expected format.format(dep))
 RuntimeError: The package version specification "ConfigAng Farse==0.15.2" do not follow the
 expected format. 
``` 

sorry for the spelling, caused by ocr.

**Comment by nicoddemus** [comment]
Hi @xiamubobby,

I've edited the original post to use inline permalink to the code, but I'm not sure about the second part. Do you mean you are having trouble specifying `ConfigArgParse ==0.15.2` in your `devenv.yml` file?

**Comment by nicoddemus** [comment]
Oh OK I get it:

```
Traceback (most recent call last):
  File "W:\Miniconda3\Scripts\conda-devenv-script.py", line 9, in <module>
    sys.exit(main())
  File "W:\Miniconda3\lib\site-packages\conda_devenv\devenv.py", line 562, in main
    conda_yaml_dict, environment = load_yaml_dict(filename)
  File "W:\Miniconda3\lib\site-packages\conda_devenv\devenv.py", line 251, in load_yaml_dict
    merged_dict = merge(all_yaml_dicts.values())
  File "W:\Miniconda3\lib\site-packages\conda_devenv\devenv.py", line 181, in merge
    merge_dependencies_version_specifications(final_dict, key_to_merge='dependencies')
  File "W:\Miniconda3\lib\site-packages\conda_devenv\devenv.py", line 210, in merge_dependencies_version_specifications
    ' expected format.'.format(dep))
RuntimeError: The package version specification "ConfigArgParse==0.15.2" do not follow the expected format.
```

The problem is that some letters on the package specification are capitalized, and the regex does not account for that. I've updated the title better describing the issue.

I think conda-devenv should account for capitalized characters (probably by ignoring case during matching).

As a workaround, you can just change the package names to all lower case:

```yaml
name: footest
dependencies:
  - configargparse==0.15.2
```

**Comment by xiamubobby** [comment]
Hi Nicodemus,

The company is blocking POST requests towards GitHub thus please ignore the spelling changes I've made and about to make. Apologies for that.

Thank you for the quick reaction indeed.
I understand that switching the matching mode to IGNORE_CASE stops the devenv files from not being able to parsed.

Still the work around I have not yet got it clearly.
By lower the package name sure conda-devenv will never complain about the problem reported as above. But will it be even possible to resolve that dependency later?
I assume not, because pip is managing packages in a case sensitive way.

Worth mentioning that the mentioned package above: ConfigArgParse is not my work but one of my expected dependencies. So I can't actually change its naming convention in PyPI.

Last but not least, thanks much for the awesome project. I'm definitely taking it anyway no matter the blocker since it solves the big problem that no one else does, especially not by Anaconda itself.

It's just for now I'm doing the hack the old way: luckily ConfigArgParse is a single script module, so I duplicated the code literals into my project.
I would definitely prefer a better solution/work around, but I think what you have suggested might not even be working anyway. Please correct me if I'm wrong.
Thanks again.

**Comment by nicoddemus** [comment]
> Hi Nicodemus,
> 
> The company is blocking POST requests towards GitHub thus please ignore the spelling mistakes I've made and about to make, because I'm using OCR for this... Apologies for that.
> 
> Thank you for the quick reaction indeed.
> I understand that switching the matching mode to IGNORE_CASE stops the devenv files from not being able to parsed.
> 
> Still the work around I have not yet got it clearly.
> By lower the package name sure conda-devenv will never complain about the problem reported as above. But will it be even possible to resolve that dependency later?
> I assume not, because pip is managing packages in a case sensitive way.

Actually `conda-devenv` just acts as a preprocessor, after that it just calls `conda env` with the resulting file (which can be inspected later).

I believe case is ignored anyway by conda and pip:

```
λ pip install configargparse
Collecting configargparse
  Downloading https://files.pythonhosted.org/packages/ee/e2/d392af39dfe241e9fa5e9830ea1f00c077c7ae1dd6ede97cba06404c66fb/ConfigArgParse-0.15.2.tar.gz
Installing collected packages: configargparse
    Running setup.py install for configargparse ... done
Successfully installed configargparse-0.15.2
```

> Last but not least, thanks much for the awesome project. I'm definitely taking it anyway no matter the blocker since it solves the big problem that no one else does, especially not by Anaconda itself.

Thanks! We have created it at ESSS for exactly those missing functionalities. 👍 
> 
> It's just for now I'm doing the hack the old way: luckily ConfigArgParse is a single script module, so I duplicated the code literals into my project.
> I would definitely prefer a better solution/work around, but I think what you have suggested might not even be working anyway. Please correct me if I'm wrong.

I think things should just work, otherwise let us know to see if there's a solution/workaround.
